/*
 * NanoXLSX4j is a small Java library to write and read XLSX (Microsoft Excel 2007 or newer) files in an easy and
 * native way
 * Copyright Raphael Stoeckli © 2026
 * This library is licensed under the MIT License.
 * You find a copy of the license in project folder or on: http://opensource.org/licenses/MIT
 */

package ch.rabanti.nanoxlsx4j.internal.interfaces.writer;

import ch.rabanti.nanoxlsx4j.Workbook;
import ch.rabanti.nanoxlsx4j.annotations.InternalApi;
import ch.rabanti.nanoxlsx4j.internal.interfaces.Plugin;
import ch.rabanti.nanoxlsx4j.utils.internal.xml.XmlElement;

/**
 * Interface, used by in-line (queue) plug-ins in XML writer classes
 */
@InternalApi
public interface PluginInlineWriter extends Plugin {

    /**
     * Gets the workbook instance, defined by the constructor
     *
     * @return Workbook instance
     */
    Workbook getWorkbook();

    /**
     * Replaces the workbook instance, defined by the constructor
     *
     * @param workbook Workbook instance
     */
    void setWorkbook(Workbook workbook);

    /**
     * Gets the write context, defined by the constructor
     *
     * @return Write context
     */
    WriteContext getWriteContext();

    /**
     * Replaces the write context, defined by the constructor
     *
     * @param writeContext Write context
     */
    void setWriteContext(WriteContext writeContext);

    /**
     * Gets the root XML element, defined by the constructor
     *
     * @return Root XML element
     */
    XmlElement getRootElement();

    /**
     * Replaces the root XML element, defined by the constructor
     *
     * @param rootElement Root XML element
     */
    void setRootElement(XmlElement rootElement);

    /**
     * Gets the current main XML element, that is generated by {@link Plugin#execute()}
     *
     * @return XML element
     */
    XmlElement getXmlElement();

    /**
     * Initialization method
     *
     * @param rootElement Reference to the root element
     * @param workbook    Workbook instance
     * @param index       Optional index, e.g. for worksheet identification
     */
    void init(XmlElement rootElement, Workbook workbook, Integer index);
}
