//STATUS: CHECKED
/*
 * NanoXLSX4j is a small Java library to write and read XLSX (Microsoft Excel 2007 or newer) files in an easy and native way
 * Copyright Raphael Stoeckli @ 2026
 * This library is licensed under the MIT License.
 * You find a copy of the license in project folder or on: http://opensource.org/licenses/MIT
 */
package ch.rabanti.nanoxlsx4j.interfaces.writer;

import ch.rabanti.nanoxlsx4j.Workbook;
import ch.rabanti.nanoxlsx4j.interfaces.IPlugin;
import ch.rabanti.nanoxlsx4j.utils.xml.XmlElement;

/**
 * Interface used by in-line (queue) plug-ins that operate inside XML writer classes.
 * <p>
 * Java equivalent of the {@code internal} .NET interface
 * {@code NanoXLSX.Interfaces.Writer.IInlinePluginWriter}.
 * </p>
 */
public interface IInlinePluginWriter extends IPlugin {

    /**
     * Gets the workbook instance used by this inline writer.
     *
     * @return the workbook
     */
    Workbook getWorkbook();

    /**
     * Sets the workbook instance for this inline writer.
     *
     * @param workbook the workbook to use
     */
    void setWorkbook(Workbook workbook);

    /**
     * Gets the root XML element passed to (and possibly updated by) {@link #init}.
     *
     * @return the root {@link XmlElement}
     */
    XmlElement getRootElement();

    /**
     * Sets the root XML element.
     *
     * @param rootElement the root {@link XmlElement}
     */
    void setRootElement(XmlElement rootElement);

    /**
     * Gets the main XML element produced by {@link #execute()}.
     *
     * @return the {@link XmlElement} generated by this inline writer
     */
    XmlElement getXmlElement();

    /**
     * Initializes this inline writer.
     *
     * @param rootElement the root element (may be updated in place; see interface note)
     * @param workbook    the workbook instance
     * @param index       optional index (e.g. for worksheet identification), or {@code null}
     */
    void init(XmlElement rootElement, Workbook workbook, Integer index);
}
