//STATUS: CHECKED
/*
 * NanoXLSX4j is a small Java library to write and read XLSX (Microsoft Excel 2007 or newer) files in an easy and native way
 * Copyright Raphael Stoeckli @ 2026
 * This library is licensed under the MIT License.
 * You find a copy of the license in project folder or on: http://opensource.org/licenses/MIT
 */
package ch.rabanti.nanoxlsx4j.interfaces.writer;

import ch.rabanti.nanoxlsx4j.interfaces.IPlugin;
import ch.rabanti.nanoxlsx4j.utils.xml.XmlElement;
import ch.rabanti.nanoxlsx4j.Workbook;

/**
 * Interface used by XML writer plug-in classes.
 * <p>
 * Java equivalent of the {@code internal} .NET interface
 * {@code NanoXLSX.Interfaces.Writer.IPluginWriter}.
 * </p>
 */
public interface IPluginWriter extends IPlugin {

    /**
     * Gets the workbook instance associated with this writer.
     *
     * @return the workbook
     */
    Workbook getWorkbook();

    /**
     * Sets the workbook instance for this writer.
     *
     * @param workbook the workbook to use
     */
    void setWorkbook(Workbook workbook);

    /**
     * Gets the main XML element produced by {@link #execute()}.
     *
     * @return the root {@link XmlElement} generated by this writer
     */
    XmlElement getXmlElement();

    /**
     * Initializes this writer from the supplied base-writer context.
     *
     * @param baseWriter the base writer providing workbook, styles, and shared-string access
     */
    void init(IBaseWriter baseWriter);
}
